---
version: '3'
services:
  orcpub:
    image: orcpub/orcpub:latest
    environment:
      PORT: 8890
      EMAIL_SERVER_URL: ''
      EMAIL_ACCESS_KEY: ''
      EMAIL_SECRET_KEY: ''
      EMAIL_SERVER_PORT: 587
      # Email address to send errors to
      EMAIL_ERRORS_TO: ''
      EMAIL_SSL: 'false'
      DATOMIC_URL: datomic:free://datomic:4334/orcpub
    depends_on:
      - datomic
    restart: always
  datomic:
    image: orcpub/datomic:latest
    volumes:
      - ./data:/data
      - ./deploy/transactor.properties:/datomic/transactor.properties
    restart: always
  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/snakeoil.crt:/etc/nginx/snakeoil.crt
      - ./deploy/snakeoil.key:/etc/nginx/snakeoil.key
    depends_on:
      - orcpub
    restart: always
