name: Continuous Integration

on: [pull_request]

jobs:
  lint:
    name: Run Linter and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.292
      - name: Load pdfbox from /lib
        run: mkdir ~/.m2/repository/ && mkdir ~/.m2/repository/org/ && cp -rv ./lib/* ~/.m2/repository
      - name: ls .m2
        run: ls -la ~/.m2/repository/org/
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          # Install just one or all simultaneously
          cli: 1.10.1.693 # Clojure CLI based on tools.deps
          lein: 2.9.1     # or use 'latest' to always provision latest version of leiningen
          boot: 2.8.3     # or use 'latest' to always provision latest version of boot
      - name: Get leiningen version
        run: lein -v
      - name: Run linter
        run: lein lint
      - name: Run tests
        run: lein test