name: Docker Releases
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        id: get_version
        run: |
          echo ::set-output name=VERSION1::${GITHUB_REF#refs/*/}
          echo ::set-output name=VERSION2::${GITHUB_REF#refs/*/v}
        shell: bash

      - name: Version
        run: |
          echo Version1: $VERSION1
          echo Version2: $VERSION2
        shell: bash

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: -7
          format: 'MM-DD-YYYY'

      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ssh-key: ${{ secrets.ACTIONSKEY }}

      - name: Update src/cljs/orcpub/ver.cljc
        run: |
          echo Version1: ${{ steps.get_version.outputs.VERSION1 }}
          echo Version2: ${{ steps.get_version.outputs.VERSION2 }}
          sed -i 's/^(defn version \[\] "*.")/\(defn version [] "${{ steps.get_version.outputs.VERSION1 }}")/' src/cljs/orcpub/ver.cljc
          sed -i 's/^(defn date \[\] "*.")/\(defn date [] "${{ steps.time.outputs.time }}")/' src/cljs/orcpub/ver.cljc
          cat src/cljs/orcpub/ver.cljc

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/orcpub/Dockerfile
          platforms: linux/amd64
          push: true
          tags: orcpub/orcpub:latest

      - name: Build and push ${{ steps.get_version.outputs.VERSION2 }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/orcpub/Dockerfile
          platforms: linux/amd64
          push: true
          tags: orcpub/orcpub:release-${{ steps.get_version.outputs.VERSION2 }}
      with:
      node-version: 15.x
      - name: Release Notes
        run: |
          npm install github-release-notes -g
          gren release --username=orcpub --repo=orcpub -D prs --override --token=${{ secrets.GREN_GITHUB_TOKEN }}
          gren changelog --username=orcpub --repo=orcpub -D prs --override --token=${{ secrets.GREN_GITHUB_TOKEN }}
      - name: Do git actions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin git@github.com:Orcpub/orcpub.git
          git fetch --all
          git checkout develop
          git add .
          git commit -m "Github Actions"
          git push



